// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdX_emaPfiScDzBu-9VnLnLen_WBXPUzA',
    appId: '1:315401592104:web:8491c7c87eb5f71f94441d',
    messagingSenderId: '315401592104',
    projectId: 'flutter-ecommerce-bf2d7',
    authDomain: 'flutter-ecommerce-bf2d7.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-bf2d7.firebasestorage.app',
    measurementId: 'G-WHRL3S409S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlgGM-aLt4nydmmR7gBRaqdl4qtPN8sq0',
    appId: '1:315401592104:android:6fb14ba16c2c943f94441d',
    messagingSenderId: '315401592104',
    projectId: 'flutter-ecommerce-bf2d7',
    storageBucket: 'flutter-ecommerce-bf2d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3MlutH0fjdgEnWvI0uKJsSlmJHmzILk',
    appId: '1:315401592104:ios:3fe0b25a5e31174f94441d',
    messagingSenderId: '315401592104',
    projectId: 'flutter-ecommerce-bf2d7',
    storageBucket: 'flutter-ecommerce-bf2d7.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU3MlutH0fjdgEnWvI0uKJsSlmJHmzILk',
    appId: '1:315401592104:ios:3fe0b25a5e31174f94441d',
    messagingSenderId: '315401592104',
    projectId: 'flutter-ecommerce-bf2d7',
    storageBucket: 'flutter-ecommerce-bf2d7.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdX_emaPfiScDzBu-9VnLnLen_WBXPUzA',
    appId: '1:315401592104:web:d704c459180e870494441d',
    messagingSenderId: '315401592104',
    projectId: 'flutter-ecommerce-bf2d7',
    authDomain: 'flutter-ecommerce-bf2d7.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-bf2d7.firebasestorage.app',
    measurementId: 'G-S1L02E3RG4',
  );
}
